spring:
  datasource:
      url: jdbc:mysql://47.103.23.138:3306/example?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: group_one
      password: 123456
mybatis:
   mapperLocations: classpath:/mapper/*.xml

